name: Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  build:
    name: Gradle 编译
    runs-on: ubuntu-latest

    steps:
      - name: 检测系统
        uses: actions/checkout@v4

      - name: 设置Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: 设置Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: 编译
        run: ./gradlew build

      - name: 上传至发布平台
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ChestcommandsX Plugin
          append_body: true
          files: |
            plugin/build/libs/chestcommands-plugin-*.jar         
